### ISSUE TITLE
Text, and Summary not being escaped, allowing apostrophe to cause problems.

### ISSUE THREAD

**Issue by neildaemond** [somatonic/MarkupSocialShareButtons#1]
For at least twitter and Linkedin, I rendered and got:

twitter:    &text=We're excited to announce the launch 
linkedin:   &summary=We're excited to announce the launch 

Note the apostrophe which caused issues with href='___' 

suggest change href='**_' to href="_**_"   or escape the fields.

**Comment by somatonic** [comment]
Thanks for the report. I had the same problem the day you reported that. I didn't had the time to make an update until now.

There seems to be various issues with special chars. Changing the href='' to href=""  would'nt work with " in the text etc. I think I found the optimal solution.

New version with a fix should appear soon.
